artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/harshmdev/projects/raw/main/corpus.zip
  local_data_file: artifacts/data_ingestion/corpus.zip
  unzip_dir: artifacts/data_ingestion